CREATE TABLE channel_user
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel          VARCHAR(255),
    external_user_id VARCHAR(255),
    external_chat_id VARCHAR(255),
    display_name     VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_channel_user PRIMARY KEY (id)
);