### Health Python
GET http://localhost:8000/health

### Health Java
GET http://localhost:8080/actuator/health

### Criar evento via Python Agent
POST http://localhost:8000/agent/message
Content-Type: application/json

{
  "text": "criar Reunião de planejamento"
}

### Listar eventos via Python Agent
POST http://localhost:8000/agent/message
Content-Type: application/json

{
  "text": "listar"
}
